### ISSUE TITLE
Implement string format method

### ISSUE THREAD

**Issue by DoDaek** [go-python/gpython#116]
## python
```
>>> a = 'alpha'
>>> b = 'bravo'
>>> d = 'delta'
>>> origin = '{} {} charlie {}'
>>> new = origin.format(a, b, d)
>>> print(new)
alpha bravo charlie delta
>>> print(origin)
{} {} charlie {}
>>>
```

## gpython 
```
>>> a = 'alpha'
>>> b = 'bravo'
>>> d = 'delta'
>>> origin = '{} {} charlie {}'
>>> new = origin.format(a, b, d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
AttributeError: "'str' has no attribute 'format'"
>>> print(new)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
NameError: "name 'new' is not defined"
>>> print(origin)
{} {} charlie {}
>>>
```

Attribute error occured using string.

**Comment by ncw** [comment]
Yes gpython needs this :-)

The specification of [the format language](https://docs.python.org/3/library/string.html#formatspec) is here so it is reasonably complicated to do completely.

**Comment by DoDaek** [comment]
It may take some time, but I'll work it out.
Thanks for your information :+1:

**Comment by tim-st** [comment]
@DoDaek 
You can have a look (or use it?) [here](https://github.com/slongfield/pyfmt).
The function should be callable using `"".format` and `str.format`

**Comment by drew-512** [comment]
Waiting on response from @slongfield 

https://github.com/slongfield/pyfmt/issues/15
