### ISSUE TITLE
builtins  id  dir function not found

### ISSUE THREAD

**Issue by QGB** [go-python/gpython#234]
```

>>> import builtins
>>> builtins.id
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: "'module' has no attribute 'id'"
>>> 
>>> builtins.dir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: "'module' has no attribute 'dir'"

``

**Comment by QGB** [comment]
sys.modules  also not support

**Comment by QGB** [comment]
```

>>> exec('print(locals())',{'1':2},{'3':3})
{'3': 3}

```
