### ISSUE TITLE
Implement bool.real, bool.imag bool.conjugate()

### ISSUE THREAD

**Issue by corona10** [go-python/gpython#73]
There are some attributes that should be implemented for gpython.

## Expected
```python
>>> a = True
>>> a.imag
0
>>> a.real
1
>>> a.conjugate()
1
```

## Actual
```python
>>> a = True
>>> a.image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
AttributeError: "'bool' has no attribute 'image'"
>>> a.real
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
AttributeError: "'bool' has no attribute 'real'"
>>> a.conjugate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
AttributeError: "'bool' has no attribute 'conjugate'"
```

**Comment by corona10** [comment]
@ncw I am going to assign this issue to the contributhon 2019 participants

**Comment by parkchansoo** [comment]
I want to take a look at this issue 🙌

**Comment by corona10** [comment]
@parkchansoo 
Please go ahead.
Here is a similar code you have to look at.

https://github.com/go-python/gpython/blob/7bc40057dc66c0ff15bb860c107b3c4664bc7b04/py/complex.go#L300
